### ISSUE TITLE
Cannot update "domain.ltd", only subdomains

### ISSUE THREAD

**Issue by bgadrian** [karalabe/cloudflare-dyndns#1]
Hello,
When I try to update a CNAME of "domain.ltd" it throws an error 

> goroutine 1 [running]:
panic(0x555bb964afc0, 0xc420014090)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
main.updateDNS(0xc42040c080, 0xa, 0x7ffeb61c3f70, 0x11, 0x7ffeb61c3f44, 0x25, 0x7ffeb61c3f2f, 0xf, 0x78, 0x0, ...)
	/work/src/github.com/karalabe/cloudflare-dyndns/main.go:100 +0xd6c
main.main()
	/work/src/github.com/karalabe/cloudflare-dyndns/main.go:50 +0x240
2017/02/17 21:55:55 Updating IP address to 5.9.62.247
panic: runtime error: index out of range

From what I see is an intended behavior, to only accept subdomains or wildcards like *.domain.ltd 
Is a bug or I am using the DNS wrong?

Thanks.

**Comment by karalabe** [comment]
This is a pretty simple tool, it can only update `A` records on sub-domains. That's useful for the typical home user/network/isp scenario. I don't want to start adding further functionality, since this package is not something I want to actively maintain, rather just have it work and do it's one thing.
